[build]
  command = "npm install && npm run build"
  publish = "build"

[context.production]
  command = "npm install && npm run build"

[context.deploy-preview]
  command = "npm install && npm run build"

[[plugins]]
  package = "netlify-plugin-cache"
    [plugins.inputs]
      paths = ["node_modules", ".cache", "build"]