[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache"

[build.environment]
  RUBY_VERSION = "3.1.2"
  NODE_VERSION = "18.20.4"