import "../styles/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";
import { Poppins } from 'next/font/google';

// Remove or comment out these lines if they're not being used
// const geistSans = GeistSans
// const geistMono = GeistMono

const poppins = Poppins({ 
  weight: ['400', '600'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body>{children}</body>
    </html>
  )
}
