import "../styles/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";
import { Poppins } from 'next/font/google';
import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'

// Remove the localFont import if it's not needed
// const geistSans = localFont({
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const poppins = Poppins({ 
  weight: ['400', '600'],
  subsets: ['latin'],
  display: 'swap',
});

const fontSans = GeistSans
const fontMono = GeistMono

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={fontSans.className}>
      <body>{children}</body>
    </html>
  )
}
